server:
  port: 8070
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://ip:3308/gmall?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false

  dubbo:
    application: user-service #dubbo中服务名称
    registry:
      address: ip:2181  #zookeeper注册中心的地址
      protocol: zookeeper #zookeeper的通信协议的名称
    protocol:
      name: dubbo #dubbo通信协议名称
    base-package: com.sunshine.insist.gmall #dubbo服务扫描的路径

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #表示表中字段携带_将其变成驼峰命名
  type-aliases-package: com.sunshine.insist.gmall.user.bean
logging:
  level:
    root: info